# -*- coding: utf-8 -*-
"""breast cancer detection svm model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA3YierKeBxpocxpi5oT2GGVd7ClUAK9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/breast-cancer-data.csv")

df.head()

df.shape

df.describe()

df.columns

"""EXPLORATORY DATA ANALYSIS"""

#since, we don't need id and Unnamed: 32, we're going to drop the columns
df = df.drop(columns=['id','Unnamed: 32'])

#verifying if the columns were dropped from the dataframe
len(df.columns)

#checking for any null values
df.isnull().sum()

df.hist(xlabelsize=5,ylabelsize=5,figsize=(15,8));

#finding the skewness of features
columns = df.columns
for col in list(columns):
  if(col=='diagnosis'):
    continue
  print(f"The skewness of {col} is {df[col].skew()}")

df['diagnosis'].value_counts()

"""MODEL BUILDING"""

X = df.drop(columns=['diagnosis'])

X.shape

y = df['diagnosis']

y.shape

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

svc_breast_cancer_classifier = Pipeline([
    ("scaler",StandardScaler()),
    ("linear_svm", SVC(kernel='linear',C=1))
])

svc_breast_cancer_classifier.fit(X_train,y_train_label)

print(f"The accuracy on the train data is {svc_breast_cancer_classifier.score(X_train,y_train_label)*100:.2f}")

svc_breast_cancer_classifier.fit(X_test,y_test_label)
print(f"The accuracy on the test data is {svc_breast_cancer_classifier.score(X_test,y_test_label)*100:.2f}")

from sklearn.model_selection import cross_val_score

# Run 5-fold Cross-Validation
scores = cross_val_score(svc_breast_cancer_classifier, X, y, cv=5)

print(f"All Scores: {scores}")
print(f"Mean Accuracy: {scores.mean() * 100:.2f}%")
print(f"Standard Deviation: {scores.std():.4f}")

import seaborn as sns
from sklearn.metrics import confusion_matrix

y_pred = svc_breast_cancer_classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign', 'Malignant'],
            yticklabels=['Benign', 'Malignant'])

plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix: Breast Cancer Detection')
plt.show()